name: app
description: "A new Flutter project."
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  salomon_bottom_bar: ^3.3.2
  fl_chart: ^0.62.0

  cupertino_icons: ^1.0.8
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  cloud_firestore: ^4.13.6

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0


flutter:


  uses-material-design: true
  assets:
    - assets/images/
