// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMjDnp4tts2Vp6k8MNttNYyAIacQMinm4',
    appId: '1:389947440709:web:9ccb723e65177ee2616d2c',
    messagingSenderId: '389947440709',
    projectId: 'food-96111',
    authDomain: 'food-96111.firebaseapp.com',
    storageBucket: 'food-96111.firebasestorage.app',
    measurementId: 'G-MZEXZX8D73',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_hwM3QeosMjh5JZm-L6_ksn2WWCSruME',
    appId: '1:389947440709:android:5cd5f5671df47959616d2c',
    messagingSenderId: '389947440709',
    projectId: 'food-96111',
    storageBucket: 'food-96111.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9YhjmVMQNQa5LR-KaDtJwhG-czJ8BYkw',
    appId: '1:389947440709:ios:f26e2019168c810d616d2c',
    messagingSenderId: '389947440709',
    projectId: 'food-96111',
    storageBucket: 'food-96111.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9YhjmVMQNQa5LR-KaDtJwhG-czJ8BYkw',
    appId: '1:389947440709:ios:f26e2019168c810d616d2c',
    messagingSenderId: '389947440709',
    projectId: 'food-96111',
    storageBucket: 'food-96111.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMjDnp4tts2Vp6k8MNttNYyAIacQMinm4',
    appId: '1:389947440709:web:3cbd6826ed71becf616d2c',
    messagingSenderId: '389947440709',
    projectId: 'food-96111',
    authDomain: 'food-96111.firebaseapp.com',
    storageBucket: 'food-96111.firebasestorage.app',
    measurementId: 'G-STE92ZLPQK',
  );
}
